[package]
name = "oathstar-auth"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
axum-extra = { workspace = true, features = ["cookie"] }
getrandom.workspace = true
oathstar-protocol = { path = "../oathstar-protocol" }
serde_json.workspace = true

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
