[package]
name = "oathstar-content"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
oathstar-core = { path = "../oathstar-core" }
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[lints]
workspace = true
